export enum UserRole {
  OWNER = "OWNER",
  CLINIC = "CLINIC",
  ADMIN = "ADMIN",
  PUBLIC_VERIFIER = "PUBLIC_VERIFIER",
}

export enum PetStatus {
  REGISTERED = "REGISTERED",
  TRANSFER_PENDING = "TRANSFER_PENDING",
  INACTIVE = "INACTIVE",
}

export enum MedicalRecordStatus {
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  REJECTED = "REJECTED",
}

export enum CorrectionStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum NotificationEventType {
  GENERAL = "GENERAL",
  MEDICAL_RECORD_PENDING = "MEDICAL_RECORD_PENDING",
  MEDICAL_RECORD_REVIEWED = "MEDICAL_RECORD_REVIEWED",
  CORRECTION_SUBMITTED = "CORRECTION_SUBMITTED",
  CORRECTION_REVIEWED = "CORRECTION_REVIEWED",
  TRANSFER_INITIATED = "TRANSFER_INITIATED",
  TRANSFER_ACCEPTED = "TRANSFER_ACCEPTED",
  TRANSFER_REJECTED = "TRANSFER_REJECTED",
  VACCINE_REMINDER = "VACCINE_REMINDER",
}
